config/routes.rb
Reto1Webimagen::Application.routes.draw do
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  
  get '/signup',  :to => 'users#new'
  get '/signin',  :to => 'sessions#new'
  get '/signout', :to => 'sessions#destroy'
  Rails.application.routes.draw do
     resources :users # or resource :user for singular resources
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :email, :password, :password_confirmation

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  # Automatically create the virtual attribute 'password_confirmation'.
  validates :username,  :presence => true,
                        :length   => { :maximum => 50 },
                        :uniqueness => true
            
  
  validates :email, :presence   => true,
                    :format     => { :with => email_regex},
                    :uniqueness => true
  
  validates :password, :presence      => true,
                       :confirmation  => true,
                       :length => { :within => 6..40 }

  before_save :encrypt_password
  def has_password?(submitted_password)
    password == encrypt(submitted_password)
  end

  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil if user.nil?
    return user if user.has_password?(submitted_password)
  end
  
  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end


  private

  def encrypt_password
    self.salt = make_salt if new_record?
    self.password = encrypt(password)
  end

  def encrypt(string)
    secure_hash("#{salt}--#{string}")
  end

  def make_salt
    secure_hash("#{Time.now.utc}--#{password}")
  end

  def secure_hash(string)
    Digest::SHA2.hexdigest(string)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    @title = "Sign in"
  end
  
  def create
    user = User.authenticate(params[:session][:email],
                             params[:session][:password])
    
    if user.nil?
      # Create an error message and re-render th signin form
      flash.now[:error] = "Invalid email/password combination."
      @title = "Sign in"
      render 'new'
    else
      # Sign the user in and redirecto to the user's show page
      sign_in user
      redirect_to user
    end
  end
  
  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    @title = "Sign up"

  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sing_in @user
      flash[:success] = "Welcome to the WebImagen!"
      redirect_to @user
    else
      @title = "Sign up"
      render 'new'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    current_user = user
  end

  def current_user(user)
    @current_user ||= user_from_remember_token
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    cookies.delete(:remember_token)
    current_user=nil
  end

  private

  def user_from_remember_token
    User.authenticate_with_salt(*remember_token)
  end

  def remember_token
    cookies.signed[:remember_token] || [nil, nil]
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header>
	<nav class="round">
		<ul>
			<% if signed_in? %>
			<li>
				<%= link_to "Sign out", signout_path, :method => :delete %>
			</li>
			<% else %>
			<li>
				<%= link_to "Sign in", signin_path %>
			</li>
			<% end %>
		</ul>
	</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Reto1Webimagen</title>
		<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<div class="container">
			<%= render 'layouts/header'%>
			
			<section class="round">
				<% flash.each do |key, value| %>
				<div class="flash <%= key %>">
					<%= value %>
				</div>
				<% end %>
			</section>
			<section>
				<%= yield %>
			</section>
			<%= debug(params) if Rails.env.development? %>
		</div>


		</body>
		</html>

app/views/users/new.html.erb
<h1>Sign up</h1>
<%= form_for(@user) do |f| %>
<div class="field">
	<%= f.label :username %>
	<br />
	<%= f.text_field :username %>
</div>
<div class="field">
	<%= f.label :email %>
	<br />
	<%= f.text_field :email %>
</div>
<div class="field">
	<%= f.label :password %>
	<br />
	<%= f.password_field :password %>
</div>
<div class="field">
	<%= f.label :password_confirmation, "Confirmation" %>
	<br />
	<%= f.password_field :password_confirmation %>
</div>
<div class="actions">
	<%= f.submit "Sign up" %>
</div>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>
<h1><%= @user.email %></h1>